name = input("Write our name: ")
old = input("How old are you: ")
town = input("Where do you live: ")
print("Your name is: {0}. \nYour age: {1}. \nYour town is: {2}. \n".format(name, old, town))
input("Press ENTER to exit")